### ISSUE TITLE
"I would like to share my metrics privately." is ambiguous

### ISSUE THREAD

**Issue by etam** [almonit/almonit-plugin#26]
It's ambiguous whether it's about sharing (choose to share or not share) or privacy (share privately or not privately).

I think it would be more clear if it was something like "I would like to share my metrics. (we care for your privacy: details)".

**Comment by eyalron33** [comment]
Good point. I rephrased it based on your suggestion in https://github.com/almonit/almonit-plugin/commit/fb6521655ac5dcaa7690d3a05cf801197f190d4f.
